// user
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// cart
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const GET_COLLECTION_BY_ID = 'GET_COLLECTION_BY_ID';
